{
  "RepeatedElements": [],
  "Request-Date": "2018-09-14T15:30:12-04:00",
  "Request-Nickname": "Nick",
  "Requester-Name": "Hub Tester1",
  "Requester-Department": "Interactive Media",
  "Requester-Email": "sp1@mos.org",
  "Requester-Phone": "617-589-3142",
  "Requester-Account": "i:0#.f|membership|sp1@mos.org",
  "Job-Title": "Title",
  "Physical-Demand-Lifting": "10",
  "Physical-Demand-Carrying": "10",
  "Physical-Demand-Pushing": "10",
  "Physical-Demand-Pulling": "10",
  "Physical-Demand-Standing": "20",
  "Physical-Demand-Sitting": "20",
  "Physical-Demand-Walking": "60",
  "Request-Status": "Pending Approval",
  "Beginning-of-Life": "1",
  "End-of-Life": "0",
  "Approval-Newly-Needed-Notify": "none",
  "Approval-Not-Needed-Notify": "none",
  "Approval-Still-Needed-Notify": "none",
  "Newly-Approved-or-Pending": "0",
  "Last-Modified-Timestamp-Mismatch": "0",
  "Admin-Email": "sp1@mos.org",
  "Request-Name": "GSE Job",
  "SWF-Version": "1.0",
  "Component-Group-Admin": "872;#Hub Tester10,#i:0#.f|membership|sp10@mos.org,#sp10@mos.org,#sp10@MOS.ORG,#Hub Tester10,#https://bmos-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/sp10_mos_org_MThumb.jpg,#Interactive Media,#;#873;#Hub Tester11,#i:0#.f|membership|sp11@mos.org,#sp11@mos.org,#sp11@MOS.ORG,#Hub Tester11,#,#Interactive Media,#;#6;#James Baker,#i:0#.f|membership|jbaker@mos.org,#jbaker@mos.org,#jbaker@mos.org,#James Baker,#https://bmos-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/jbaker_mos_org_MThumb.jpg?t=63616027741,#Interactive Media,#Intranet Solutions Project Manager;#20;#Ben Wilson,#i:0#.f|membership|bwilson@mos.org,#bwilson@mos.org,#bwilson@mos.org,#Ben Wilson,#https://bmos-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/bwilson_mos_org_MThumb.jpg,#Interactive Media,#Director of Digital &amp; Interactive Media;#467;#Samuel Corey,#i:0#.f|membership|scorey@mos.org,#scorey@mos.org,#scorey@MOS.ORG,#Samuel Corey,#https://bmos-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/scorey_mos_org_MThumb.jpg,#Interactive Media,#Web Developer",
  "Component-Admin": "30;#Christine Flebbe,#i:0#.f|membership|cflebbe@mos.org,#cflebbe@mos.org,#cflebbe@mos.org,#Christine Flebbe,#https://bmos-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/cflebbe_mos_org_MThumb.jpg,#Human Resources,#Manager,, Compensation &amp; Benefits;#427;#Lorah Broderick,#i:0#.f|membership|lbroderick@mos.org,#lbroderick@mos.org,#lbroderick@mos.org,#Lorah Broderick,#https://bmos-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/lsnow_mos_org_MThumb.jpg,#Human Resources,#Benefits &amp; Employee Programs Administrator;#29;#Margo Smith,#i:0#.f|membership|msmith@mos.org,#msmith@mos.org,#msmith@mos.org,#Margo Smith,#https://bmos-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/msmith_mos_org_MThumb.jpg,#Human Resources,#Manager,, Talent Acquisition &amp; Development",
  "Current-User-Display-Name": "Hub Tester1",
  "Current-User-Name": "sp1@mos.org",
  "Current-User-is-Admin": "1",
  "Current-User-is-Component-Group-Admin": "0",
  "Component-ID": "158",
  "Self-or-Other": "Talk to me",
  "Department": "Accessibility",
  "Job-Description": "This is the JD.",
  "Training-Requirements": "This is a.%0ARequirement.",
  "Dress-Requirements": "This is a.%0ARequirement.",
  "Job-Duties": "This is a.%0ADuty.",
  "User-Machine-History": "September 14, 2018 3:30 pm - Firefox 61.0 - probably desktop - Linux %0A %0A",
  "Requested-For": [{
    "account": "i:0#.f|membership|sp1@mos.org",
    "displayText": "Hub Tester1",
    "description": "sp1@mos.org"
  }],
  "Requested-By": "",
  "Job-Admin": [{
    "account": "i:0#.f|membership|sp1@mos.org",
    "displayText": "Hub Tester1",
    "description": "sp1@mos.org"
  }]
}
